import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "orgchart/dist/css/jquery.orgchart.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Solarflux - Solar Monitoring",
  description: "Generated by create next app",
  icons: {
    icon: "/company.png", // Correct way
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/company.png" type="image/png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}